server: 
  port: 3344 
  
spring:
  application:
    name: spring-cloud-example-config
  cloud:
    config:
      server:
        git:
          uri:  git@github.com:xiaozhi521/spring-cloud-example-config.git #GitHub上面的git仓库名字
 

